name: 정기 빌드

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  call-deploy-hook:
    runs-on: ubuntu-latest
    steps:
      - name: Vercel Deploy Hook 호출
        run: curl -X POST ${{ secrets.DEPLOY_HOOK_URL }}
